# Generated by Django 6.0.1 on 2026-04-11 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operatives', '0001_initial'),
        ('parcelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurningPlanPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bp_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('responsible', models.CharField(blank=True, default='', max_length=200)),
                ('scheduled_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Pre-Plano', 'Pré-Plano'), ('Executada', 'Executada')], default='Pre-Plano', max_length=20)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcels', models.ManyToManyField(related_name='fire_actions', to='parcelas.fireparcel')),
            ],
            options={
                'verbose_name': 'Pré-Plano',
                'verbose_name_plural': 'Pré-Planos',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='BurningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField()),
                ('num_men', models.IntegerField(blank=True, null=True)),
                ('vehicles', models.TextField(blank=True, default='{}')),
                ('problems', models.TextField(blank=True, default='')),
                ('fuel_superficial', models.CharField(blank=True, default='', max_length=20)),
                ('fuel_manta_f', models.CharField(blank=True, default='', max_length=20)),
                ('fuel_manta_h', models.CharField(blank=True, default='', max_length=20)),
                ('weather_state', models.CharField(blank=True, default='', max_length=80)),
                ('wind_speed_beaufort', models.CharField(blank=True, default='', max_length=10)),
                ('wind_speed_kmh', models.CharField(blank=True, default='', max_length=20)),
                ('wind_direction', models.CharField(blank=True, default='', max_length=20)),
                ('fire_conduct', models.CharField(blank=True, choices=[('1', '1 — Contra o vento / contra o declive'), ('2', '2 — Por linhas sucessivas'), ('3', '3 — Perimetral'), ('4', '4 — De flanco'), ('5', '5 — Outro')], default='', max_length=2)),
                ('fire_conduct_other', models.TextField(blank=True, default='')),
                ('burn_effects', models.TextField(blank=True, default='')),
                ('burn_efficiency', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operatives', models.ManyToManyField(blank=True, related_name='burning_plans', to='operatives.operative')),
                ('photos', models.ManyToManyField(blank=True, to='fire_actions.burningplanphoto')),
                ('pre_plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='burningplan', to='fire_actions.fireaction')),
            ],
            options={
                'verbose_name': 'Plano de Queima',
                'verbose_name_plural': 'Planos de Queima',
                'ordering': ['-execution_date'],
            },
        ),
        migrations.CreateModel(
            name='PrePlanPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='preplan_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fire_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preplan_photos', to='fire_actions.burningplan')),
            ],
        ),
    ]
