# Generated by Django 6.0.1 on 2026-04-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='burningplan',
            name='tactical_schema',
            field=models.ImageField(blank=True, null=True, upload_to='tactical_schemas/'),
        ),
    ]
