# Generated by Django 6.0.1 on 2026-04-11 18:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('concelho', models.CharField(blank=True, default='', max_length=100)),
                ('vegetation_type', models.CharField(choices=[('matos', 'Matos'), ('pinhal', 'Pinhal'), ('eucaliptal', 'Eucaliptal'), ('misto', 'Misto')], default='matos', max_length=20)),
                ('infrastructure', models.CharField(choices=[('non_existing', 'Inexistente'), ('existing', 'Operacional'), ('req_maintenance', 'Manutenção necessária'), ('no_info', 'Sem informação')], default='no_info', max_length=50)),
                ('owner_info', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], default='no', max_length=20)),
                ('resp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('resp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_burned_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['name'],
            },
        ),
    ]
